FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Expose ports
EXPOSE 3002 1234

# Start in dev mode
CMD ["npm", "run", "dev"]
